steps:
  - checkout
  - run:
      name: Install dependencies with poetry
      command: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
  - run:
      name: Run tests
      command: |
        python manage.py test
  # Other steps...
